#!/bin/sh
set -e
# This script runs both unit and functional tests using [coverage][1], and
# combine the results in one file to get the union of both tests.
#
# [1]: https://pypi.org/project/coverage/

cd $(dirname $0)/..

python3-coverage run -p --source doxyqml tests/unit/tests.py
python3-coverage run -p --source doxyqml tests/functional/tests.py --import

python3-coverage combine
